### ISSUE TITLE
Using package injects CSS at the end of the head tag

### ISSUE THREAD

**Issue by RobertDoc** [couds/react-bulma-switch#2]
I was initially using this package on a project but had to subsequently remove it as it was the cuplrit of injecting a:
```
body {
color: #4a4a4a; 
}
```

after all of my CSS, which I was not able to see documented anywhere and I have overridden on bulma itself.

**Comment by couds** [comment]
Hi @RobertDoc Sorry but I'm not maintaining this anymore. (I just updated the Readme)
